[2022-02-24 23:36:38,737] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: daily_fuel_data_ingestion.delete_local_files_task manual__2022-02-24T22:55:20.271881+00:00 [queued]>
[2022-02-24 23:36:38,747] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: daily_fuel_data_ingestion.delete_local_files_task manual__2022-02-24T22:55:20.271881+00:00 [queued]>
[2022-02-24 23:36:38,747] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 23:36:38,747] {taskinstance.py:1244} INFO - Starting attempt 7 of 8
[2022-02-24 23:36:38,748] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 23:36:38,759] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): delete_local_files_task> on 2022-02-24 22:55:20.271881+00:00
[2022-02-24 23:36:38,766] {standard_task_runner.py:52} INFO - Started process 2101 to run task
[2022-02-24 23:36:38,771] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'daily_fuel_data_ingestion', 'delete_local_files_task', 'manual__2022-02-24T22:55:20.271881+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/ingest_daily_fuel_data_dag.py', '--cfg-path', '/tmp/tmpsxw_od96', '--error-file', '/tmp/tmpnng61_cd']
[2022-02-24 23:36:38,772] {standard_task_runner.py:77} INFO - Job 25: Subtask delete_local_files_task
[2022-02-24 23:36:38,829] {logging_mixin.py:109} INFO - Running <TaskInstance: daily_fuel_data_ingestion.delete_local_files_task manual__2022-02-24T22:55:20.271881+00:00 [running]> on host 036a2a858d52
[2022-02-24 23:36:38,883] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_fuel_data_ingestion
AIRFLOW_CTX_TASK_ID=delete_local_files_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T22:55:20.271881+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-24T22:55:20.271881+00:00
[2022-02-24 23:36:38,884] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-24 23:36:38,885] {subprocess.py:74} INFO - Running command: ['bash', '-c', "rm /opt/***/daily_fuel_data_{ execution_date.strftime('%d-%b-%Y') }.csv /opt/***/daily_fuel_data_{ execution_date.strftime('%d-%b-%Y') }.parquet"]
[2022-02-24 23:36:38,900] {subprocess.py:85} INFO - Output:
[2022-02-24 23:36:38,902] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `('
[2022-02-24 23:36:38,903] {subprocess.py:89} INFO - bash: -c: line 0: `rm /opt/***/daily_fuel_data_{ execution_date.strftime('%d-%b-%Y') }.csv /opt/***/daily_fuel_data_{ execution_date.strftime('%d-%b-%Y') }.parquet'
[2022-02-24 23:36:38,903] {subprocess.py:93} INFO - Command exited with return code 1
[2022-02-24 23:36:38,918] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-02-24 23:36:38,925] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_fuel_data_ingestion, task_id=delete_local_files_task, execution_date=20220224T225520, start_date=20220224T233638, end_date=20220224T233638
[2022-02-24 23:36:38,939] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task delete_local_files_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-02-24 23:36:38,984] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-24 23:36:39,018] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
